name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ secrets.DOCKERHUB_USERNAME }}/devops-labs:latest
          containerAppName: devops-app
          containerAppEnvironment: devops-app-env
          resourceGroup: devsecops-lab
          location: australiaeast
          targetPort: 5000
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Verify image signature
        env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/devops-labs:latest
          GITHUB_ISSUER: https://token.actions.githubusercontent.com
          CERT_IDENTITY_REGEXP: https://github.com/.*/<YOUR_GITHUB_REPOSITORY_NAME>/.github/workflows/ci-pipeline.yml.*
        run: |
          cosign verify $IMAGE  --certificate-identity-regexp $CERT_IDENTITY_REGEXP  --certificate-oidc-issuer $GITHUB_ISSUER

  submit_results:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Azure CLI script
        id: token-gen
        run: |
          ACCESS_TOKEN=$(az account get-access-token | jq -r .accessToken)
          if [ -z "$ACCESS_TOKEN" ]; then
            echo "Failed to retrieve ACCESS_TOKEN"
            exit 1
          fi
          echo "AZURE_ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Retrieve FQDN
        run: |
          export FQDN=$(az containerapp show -n devops-app -g devsecops-lab --query properties.configuration.ingress.fqdn -o tsv)
          if [ -z "$FQDN" ]; then
            echo "Failed to retrieve FQDN. Exiting."
            exit 1
          else
            echo "FQDN: $FQDN"
          fi
          echo "FQDN=$FQDN" >> $GITHUB_ENV

      - name: Upload reports
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          AZURE_ACCESS_TOKEN: ${{ env.AZURE_ACCESS_TOKEN }}
          FQDN: ${{ env.FQDN }}
        run: |
          WEEK1_APP=$(curl -X POST -H "Authorization: Bearer $AZURE_ACCESS_TOKEN" -d "https://$FQDN" https://devsecops-ver.azurewebsites.net/api/week1-app)
          echo "Week1 app upload: $WEEK1_APP"
          
          WEEK2_SUBMIT=$(curl -X POST -H "Authorization: Bearer $AZURE_ACCESS_TOKEN" -d "https://$FQDN" https://devsecops-ver.azurewebsites.net/api/week2-submit)
          echo "Week2 submit: $WEEK2_SUBMIT"
