name: Python test and build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest api_tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: test-results
          path: junit/test-results.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Add your build steps here if required
      - name: Placeholder for Build Steps
        run: echo "Build steps go here"

  submit_results:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - uses: azure/login@v1.5.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Azure Access Token and Upload Reports
        env:
          AZURE_ACCESS_TOKEN: ${{ secrets.AZURE_ACCESS_TOKEN }}
        run: |
          ACCESS_TOKEN=$(az account get-access-token | jq -r .accessToken)
          echo "Azure Access Token Acquired"

          WEEK1_CONTAINER=$(curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" -d "$DOCKERHUB_USERNAME/devops-labs" https://devsecops-ver.azurewebsites.net/api/week1-container)
          echo "Week1 container upload: $WEEK1_CONTAINER"
