name: Python test and image scan

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest api_tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: junit/test-results.xml

  sonarqube:
    if: false  # Disable this job to skip SonarQube
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}

  dast:
    if: false  # Disable this job to skip DAST
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: DAST Scan
        run: echo "DAST scan steps here..."

  image-scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        uses: anchore/scan-action@v3
        id: image-scan
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/devops-labs:latest
          fail-build: false
          output-format: json

      - name: Upload Image report
        uses: actions/upload-artifact@v4
        with:
          name: image-report
          path: ${{ steps.image-scan.outputs.json }}

  build:
    if: false  # Disable this job to skip the build process
    needs: [sonarqube, dast, image-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        run: echo "Build steps here..."

  submit_reports:
    if: false  # Disable this job to skip report submission
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Submit reports
        run: echo "Report submission steps here..."
